---
require:
  - cookstyle

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - "**/*.rb"
  Exclude:
    - "vendor/**/*"
    - "spec/**/*"

# Disable string literal style check to reduce changes when migrating from chefstyle
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
Layout/TrailingWhitespace:
  Exclude:
    - "spec/unit/fixtures/**/*"
Style/PercentLiteralDelimiters:
  Exclude:
    - "lib/chef-cli/skeletons/**/*"
Layout/TrailingEmptyLines:
  Exclude:
    - "spec/unit/fixtures/**/*"
