---
require:
  - cookstyle

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - "**/*.rb"
  Exclude:
    - "vendor/**/*"
    - "spec/**/*"
    - "lib/chef-cli/skeletons/code_generator"
    - "spec/unit/fixtures/chef-runner-cookbooks"
    - "spec/unit/fixtures/cookbook_cache"
    - "spec/unit/fixtures/example_cookbook"
    - "spec/unit/fixtures/example_cookbook_metadata_json_only"
    - "spec/unit/fixtures/example_cookbook_no_metadata"
    - "spec/unit/fixtures/local_path_cookbooks"

# Disable string literal style check to reduce changes when migrating from chefstyle
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
Layout/TrailingWhitespace:
  Exclude:
    - "spec/unit/fixtures/**/*"
Style/PercentLiteralDelimiters:
  Exclude:
    - "lib/chef-cli/skeletons/**/*"
Layout/TrailingEmptyLines:
  Exclude:
    - "spec/unit/fixtures/**/*"
