---
require:
  - chefstyle

AllCops:
  TargetRubyVersion: 3.1
  Include:
      - "**/*.rb"
  Exclude:
      - "vendor/**/*"
      - "spec/**/*"
Style/StringLiterals:
  Exclude:
    - "spec/unit/fixtures/**/*"
    - "lib/chef-cli/skeletons/**/*"
Layout/TrailingWhitespace:
  Exclude:
    - "spec/unit/fixtures/**/*"
Style/PercentLiteralDelimiters:
  Exclude:
    - "lib/chef-cli/skeletons/**/*"
Layout/TrailingEmptyLines:
  Exclude:
    - "spec/unit/fixtures/**/*"
